spring:
  application:
    name: drei-alben-proxy
server:
  servlet:
    context-path: /api

app:
  external:
    ddfdbBaseUrl: https://www.ddfdb.de
    dieDreiMetadatenUrl: https://dreimetadaten.de/data/
    secret: ${DDFDB_API_KEY:secret}